
@baseUrl = http://localhost:8100/api
# @baseUrl = https://app-latest-4nnj.onrender.com/api
@token = ""
@refreshToken = ""




###GET CSRF TOKEN###
# @name csrf
GET http://localhost:8100/api/csrf
Accept: application/json

@csrfToken = {{csrf.response.body.csrfToken}}

### REGISTER
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name": "User",
    "email": "user@example.com",
    "password": "password123"
}

### LOGIN & GET TOKEN
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "password123"
}

@token = {{login.response.body.token}}
@refreshToken = {{login.response.body.refreshToken}}